def swapping():
    file1=open("sample1.txt", "a")
    file2=open("sample2.txt", "a")
    file1=open("sample1.txt", "r")
    file2=open("sample2.txt", "r")
    cont1=file1.read()
    cont2=file2.read()
    file1=open("sample1.txt", "w")
    file2=open("sample2.txt", "w")
    file1.write(cont2)
    file2.write(cont1)
    file1.seek(0)
    file2.seek(0)
swapping()

import time
    
print("Data has been changed. Check the files")
print('.', end='')
time.sleep(0.75)
print('.', end='')
time.sleep(0.75)
print('.')
time.sleep(0.75)
print("Well, let me do that instead")
file1=open("sample1.txt", "r")
file2=open("sample2.txt", "r")
time.sleep(0.5)
print("File 1 :", file1.read())
time.sleep(0.5)
print("File 2 :", file2.read())
